version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:wdifQgL6CBRNOE7GHVDbD5VqgCsDWwJYEObZI3iCT68=
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: "laravel_belleza"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
